
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label2;
	private global::Gtk.Entry TALength_txtbox;
	private global::Gtk.Label label3;
	private global::Gtk.Entry TAWidth_txtbox;
	private global::Gtk.Button Config_btn;
	private global::Gtk.Button Reset_btn;
	private global::Gtk.Label label4;
	private global::Gtk.Label TotArea_lbl;
	private global::Gtk.Label label1;
	private global::Gtk.Entry M1X_txtbox;
	private global::Gtk.Label label5;
	private global::Gtk.Entry M1Y_txtbox;
	private global::Gtk.Image Mote;
	private global::Gtk.Button Begin;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Target Area Length");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 30;
		w1.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TALength_txtbox = new global::Gtk.Entry ();
		this.TALength_txtbox.CanFocus = true;
		this.TALength_txtbox.Name = "TALength_txtbox";
		this.TALength_txtbox.IsEditable = true;
		this.TALength_txtbox.InvisibleChar = '•';
		this.fixed1.Add (this.TALength_txtbox);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.TALength_txtbox]));
		w2.X = 173;
		w2.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Target Area Width");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w3.X = 32;
		w3.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TAWidth_txtbox = new global::Gtk.Entry ();
		this.TAWidth_txtbox.CanFocus = true;
		this.TAWidth_txtbox.Name = "TAWidth_txtbox";
		this.TAWidth_txtbox.IsEditable = true;
		this.TAWidth_txtbox.InvisibleChar = '•';
		this.fixed1.Add (this.TAWidth_txtbox);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.TAWidth_txtbox]));
		w4.X = 171;
		w4.Y = 78;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Config_btn = new global::Gtk.Button ();
		this.Config_btn.CanFocus = true;
		this.Config_btn.Name = "Config_btn";
		this.Config_btn.UseUnderline = true;
		this.Config_btn.Label = global::Mono.Unix.Catalog.GetString ("Configure Area");
		this.fixed1.Add (this.Config_btn);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Config_btn]));
		w5.X = 941;
		w5.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Reset_btn = new global::Gtk.Button ();
		this.Reset_btn.CanFocus = true;
		this.Reset_btn.Name = "Reset_btn";
		this.Reset_btn.UseUnderline = true;
		this.Reset_btn.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.fixed1.Add (this.Reset_btn);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Reset_btn]));
		w6.X = 967;
		w6.Y = 86;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Total Area =");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w7.X = 66;
		w7.Y = 118;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TotArea_lbl = new global::Gtk.Label ();
		this.TotArea_lbl.Name = "TotArea_lbl";
		this.TotArea_lbl.LabelProp = global::Mono.Unix.Catalog.GetString ("- - - - -");
		this.fixed1.Add (this.TotArea_lbl);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.TotArea_lbl]));
		w8.X = 172;
		w8.Y = 119;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Mote 1 - X Coordinate");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w9.X = 397;
		w9.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.M1X_txtbox = new global::Gtk.Entry ();
		this.M1X_txtbox.CanFocus = true;
		this.M1X_txtbox.Name = "M1X_txtbox";
		this.M1X_txtbox.IsEditable = true;
		this.M1X_txtbox.InvisibleChar = '•';
		this.fixed1.Add (this.M1X_txtbox);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.M1X_txtbox]));
		w10.X = 554;
		w10.Y = 34;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Mote 1 - Y Coordinate");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w11.X = 399;
		w11.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.M1Y_txtbox = new global::Gtk.Entry ();
		this.M1Y_txtbox.CanFocus = true;
		this.M1Y_txtbox.Name = "M1Y_txtbox";
		this.M1Y_txtbox.IsEditable = true;
		this.M1Y_txtbox.InvisibleChar = '•';
		this.fixed1.Add (this.M1Y_txtbox);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.M1Y_txtbox]));
		w12.X = 552;
		w12.Y = 76;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Mote = new global::Gtk.Image ();
		this.Mote.Name = "Mote";
		this.Mote.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("GUI_V2.antenna-parabola.png");
		this.fixed1.Add (this.Mote);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Mote]));
		w13.X = 99;
		w13.Y = 331;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Begin = new global::Gtk.Button ();
		this.Begin.CanFocus = true;
		this.Begin.Name = "Begin";
		this.Begin.UseUnderline = true;
		this.Begin.Label = global::Mono.Unix.Catalog.GetString ("Begin");
		this.fixed1.Add (this.Begin);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Begin]));
		w14.X = 968;
		w14.Y = 15;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1130;
		this.DefaultHeight = 862;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Config_btn.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.Reset_btn.Clicked += new global::System.EventHandler (this.OnResetBtnClicked);
		this.Begin.Clicked += new global::System.EventHandler (this.OnBeginClicked);
	}
}
